project_id = "jcsjqnjvnqqghiaawhcl"

[functions.migrate-airtable-projects]
verify_jwt = false

[functions.enhance-text]
verify_jwt = false

[functions.enhance-prompt]
verify_jwt = false

[functions.page-builder-chat]
verify_jwt = false

[functions.firecrawl-scrape]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.sitemap-dynamic]
verify_jwt = false

[functions.github-repos]
verify_jwt = false

[functions.send-newsletter]
verify_jwt = false

[functions.og-blog]
verify_jwt = false
