project_id = "jcsjqnjvnqqghiaawhcl"

[functions.migrate-airtable-projects]
verify_jwt = false

[functions.enhance-text]
verify_jwt = false

[functions.page-builder-chat]
verify_jwt = false

[functions.firecrawl-scrape]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false
